# Generated by Django 2.1.5 on 2021-03-27 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_forumreminder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcomment',
            old_name='user',
            new_name='author',
        ),
    ]
