# Generated by Django 2.1.5 on 2021-08-26 08:11

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import freebie.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Freebie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, default='')),
                ('header_image', models.ImageField(blank=True, null=True, upload_to=freebie.models.Freebie.shareable_header_directory)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('orig_sharer', models.TextField(default='Item/Information was from Mobilarian Facebook group.', max_length=255)),
                ('category', models.CharField(default='E-book', help_text="Send me an email if there's no correct category for your share. :)", max_length=50)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Orig_Sharer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('profile_link1', models.URLField(max_length=150)),
                ('profile_link2', models.URLField(blank=True, help_text='Not needed if sharer has no other profile links.', max_length=150, null=True)),
                ('profile_link3', models.URLField(blank=True, help_text='Not needed if sharer has no other profile links.', max_length=150, null=True)),
            ],
        ),
    ]
