# Generated by Django 2.1.5 on 2021-05-15 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orig_sharer',
            name='profile_link2',
            field=models.URLField(blank=True, help_text='Not needed if sharer has no other profile links.', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='orig_sharer',
            name='profile_link3',
            field=models.URLField(blank=True, help_text='Not needed if sharer has no other profile links.', max_length=150, null=True),
        ),
    ]
