# Generated by Django 2.1.5 on 2021-07-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareable', '0002_auto_20210515_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareable',
            name='orig_sharer',
            field=models.TextField(default='Item/Information was from Mobilarian Facebook group.', max_length=255),
        ),
    ]
